function [fnm_metric]=get_fnm_metric(pnm,n_i,n_j,n_k)
fnm_metric=[pnm 'swmpi'  ...
            num2str(n_i,'%2.2i') ...
            num2str(n_j,'%2.2i') ...
            num2str(n_k,'%2.2i') ...
            '_metric.nc'];
